version: '3.8'

services:
  my-postgres: # Define PostgreSQL service
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_DB=${DB_NAME}  # Set PostgresSQL database name
      - POSTGRES_USER=${DB_USERNAME}  # Set PostgresSQL username
      - POSTGRES_PASSWORD=${DB_PASSWORD}  # Set PostgresSQL password
    ports:
      - '5433:5432'  # Map container port 5432 to host port 5433
    volumes:
      - pg_data:/var/lib/postgresql/data  # Mount volume for PostgreSQL data

  web: # Define web application service
    build: .  # Build Docker image from the current directory
    container_name: betterapp
    ports:
      - '8081:8080'  # Map container port 8080 to host port 8081
    volumes:
      - .:/app  # Mount current directory to /app inside the container
    environment:
      - DB_HOST=my-postgres  # Set the database host to "my-postgres"
      - DB_PORT=5432  # Set the database port to 5432
      - DB_USERNAME=${DB_USERNAME}  # Set the database username
      - DB_PASSWORD=${DB_PASSWORD}  # Set the database password
      - DB_NAME=${DB_NAME}  # Set the database name
      - SSL_MODE=${SSL_MODE}  # Set the SSL mode for the database connection

    depends_on:
      - my-postgres  # Specify the dependency on the PostgreSQL service

volumes:
  pg_data:  # Define a named volume for PostgreSQL data storage
